DEFAULT_PORT = 4000
DEFAULT_USERNAME = 'user'
DEFAULT_PASSWORD = 'password'
DEFAULT_SECRET_KEY = 'secret_key'
DEFAULT_JSON_RESPONSE = {'message': 'This is the default JSON response'}
DEFAULT_CLIENT_ID = 'client_id_example'
DEFAULT_CLIENT_SECRET = 'client_secret_example'
GRANT_TYPE = 'client_credentials'
DEFAULT_EXPIRATION_TIME = 30  # In minutes
DEFAULT_API_KEY = 'api_key_example'
